/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TournamentApi);
  }
}(this, function(expect, TournamentApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TournamentApi.MatchStatusPlayersInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MatchStatusPlayersInner', function() {
    it('should create an instance of MatchStatusPlayersInner', function() {
      // uncomment below and update the code to test MatchStatusPlayersInner
      //var instance = new TournamentApi.MatchStatusPlayersInner();
      //expect(instance).to.be.a(TournamentApi.MatchStatusPlayersInner);
    });

    it('should have the property player (base name: "player")', function() {
      // uncomment below and update the code to test the property player
      //var instance = new TournamentApi.MatchStatusPlayersInner();
      //expect(instance).to.be();
    });

    it('should have the property matchDetails (base name: "match_details")', function() {
      // uncomment below and update the code to test the property matchDetails
      //var instance = new TournamentApi.MatchStatusPlayersInner();
      //expect(instance).to.be();
    });

  });

}));
