version: "3"

services:
  postgres:
    build:
      context: postgres/
    container_name: "postgres"
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: web/
    container_name: "web"
    ports:
      - "8080:8080"
    # volumes:
    #   - web_data:/var/www/html

  nginx:
    build:
      context: web/
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - nginx.conf:/etc/nginx/nginx.conf
    #   - certs:/etc/nginx/certs

  api:
    build:
      context: api/
    container_name: "api"
    ports:
      - "8000:8000"

# volumes:
#   postgres_data:
#   web_data:
#   nginx.conf:
#   certs:
