services:
  rdbms:
    image: postgres:16-alpine
    container_name: "rdbms"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - vol_rdbms:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - net_pong

  static-builder:
    build:
      context: .
      dockerfile: static-builder/Dockerfile
      target: build
      args:
        - VITE_API_URL
        - VITE_WEBSOCKET_URL
    container_name: "static-builder"
    volumes:
      - vol_static_builder:/usr/src/vite

  reverseproxy:
    container_name: "reverseproxy"
    image: nginx:1.26.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverseproxy/ssl/:/etc/ssl/
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - vol_static_builder:/usr/share/nginx/html # vol_static_builderをマウント
      - vol_avatars_data:/var/www/data/avatars
    networks:
      - net_pong
    depends_on:
      api:
        condition: service_healthy
      rdbms:
        condition: service_healthy
      static-builder:
        condition: service_completed_successfully

  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
      target: deploy_asgi
    container_name: "api"
    expose:
      - "8000"
    networks:
      - net_pong
    volumes:
      - vol_avatars_data:/var/www/data/avatars
      - vol_logs:/var/log/django
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      rdbms:
        condition: service_healthy
      in_memory_db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-H",
          "Host: reverseproxy",
          "http://localhost:8000/health/",
        ]
      interval: 5s
      retries: 5

  in_memory_db:
    container_name: "in_memory_db"
    image: redis:7.4.2
    networks:
      - net_pong
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  net_pong:
    driver: bridge
    name: "net_pong"

volumes:
  vol_rdbms:
    name: "vol_rdbms"
  vol_static_builder:
    name: "vol_static_builder"
  vol_avatars_data:
    name: "vol_avatars_data"
  vol_logs:
    name: "vol_logs"

