services:
  rdbms:
    image: postgres:16-alpine
    container_name: "rdbms"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - net_pong

  static-builder:
    build:
      context: static-builder/
    container_name: "static-builder"

  reverseproxy:
    build:
      context: reverseproxy/
    container_name: "reverseproxy"
    image: nginx:1.26.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # TODO mount ssl/tls certificate volume
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net_pong

  api:
    build:
      context: api/
    container_name: "api"
    networks:
      - net_pong

networks:
  net_pong:
    name: "net_pong"

volumes:
  vol_reverseproxy:
    name: "vol_reverseproxy"
  vol_rdbms:
    name: "vol_rdbms"
