# Generated by Django 4.2 on 2025-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '申請中'), ('accepted', '承認済み'), ('rejected', '拒否')], default='pending', max_length=10)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
    ]
