# Djangoの開発環境用
services:
  # バックエンドのサービス
  api:
    build:
      context: ../../
      dockerfile: ./api/Dockerfile
      target: deploy_asgi # 開発用のDockerfileのターゲット
    ports:
      - "8000:8000"
    networks:
      - pong_network
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      rdbms:
        condition: service_healthy
      in_memory_db:
        condition: service_healthy
    container_name: "dev-api"

  rdbms:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - pong_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pong_user"]
      interval: 15s
      retries: 5
    container_name: "dev-rdbms"

  in_memory_db:
    image: redis:latest
    networks:
      - pong_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 15s
      retries: 5
    container_name: "in_memory_db"

volumes:
  postgres_data:

networks:
  pong_network:
    driver: bridge
