/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ErrorResponse from './model/ErrorResponse';
import MatchDetails from './model/MatchDetails';
import MatchStatus from './model/MatchStatus';
import MatchStatusPlayersInner from './model/MatchStatusPlayersInner';
import Player from './model/Player';
import Score from './model/Score';
import TournamentPlayer from './model/TournamentPlayer';
import TournamentRequest from './model/TournamentRequest';
import TournamentResponse from './model/TournamentResponse';
import TournamentResponseParticipantsInner from './model/TournamentResponseParticipantsInner';
import LocalPlayApi from './api/LocalPlayApi';


/**
* トーナメント、試合、プレイヤーの管理用API。.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TournamentApi = require('index'); // See note below*.
* var xxxSvc = new TournamentApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TournamentApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TournamentApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TournamentApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The MatchDetails model constructor.
     * @property {module:model/MatchDetails}
     */
    MatchDetails,

    /**
     * The MatchStatus model constructor.
     * @property {module:model/MatchStatus}
     */
    MatchStatus,

    /**
     * The MatchStatusPlayersInner model constructor.
     * @property {module:model/MatchStatusPlayersInner}
     */
    MatchStatusPlayersInner,

    /**
     * The Player model constructor.
     * @property {module:model/Player}
     */
    Player,

    /**
     * The Score model constructor.
     * @property {module:model/Score}
     */
    Score,

    /**
     * The TournamentPlayer model constructor.
     * @property {module:model/TournamentPlayer}
     */
    TournamentPlayer,

    /**
     * The TournamentRequest model constructor.
     * @property {module:model/TournamentRequest}
     */
    TournamentRequest,

    /**
     * The TournamentResponse model constructor.
     * @property {module:model/TournamentResponse}
     */
    TournamentResponse,

    /**
     * The TournamentResponseParticipantsInner model constructor.
     * @property {module:model/TournamentResponseParticipantsInner}
     */
    TournamentResponseParticipantsInner,

    /**
    * The LocalPlayApi service constructor.
    * @property {module:api/LocalPlayApi}
    */
    LocalPlayApi
};
