/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ErrorResponse from './model/ErrorResponse';
import MatchDetail from './model/MatchDetail';
import MatchResponse from './model/MatchResponse';
import MatchResponsePlayersInner from './model/MatchResponsePlayersInner';
import Player from './model/Player';
import ScoreRequest from './model/ScoreRequest';
import ScoreResponse from './model/ScoreResponse';
import TournamentPlayer from './model/TournamentPlayer';
import TournamentRequest from './model/TournamentRequest';
import TournamentResponse from './model/TournamentResponse';
import TournamentResponseParticipantsInner from './model/TournamentResponseParticipantsInner';
import DefaultApi from './api/DefaultApi';


/**
* トーナメント、試合、プレイヤーの管理用API。.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TournamentApi = require('index'); // See note below*.
* var xxxSvc = new TournamentApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TournamentApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TournamentApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TournamentApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The MatchDetail model constructor.
     * @property {module:model/MatchDetail}
     */
    MatchDetail,

    /**
     * The MatchResponse model constructor.
     * @property {module:model/MatchResponse}
     */
    MatchResponse,

    /**
     * The MatchResponsePlayersInner model constructor.
     * @property {module:model/MatchResponsePlayersInner}
     */
    MatchResponsePlayersInner,

    /**
     * The Player model constructor.
     * @property {module:model/Player}
     */
    Player,

    /**
     * The ScoreRequest model constructor.
     * @property {module:model/ScoreRequest}
     */
    ScoreRequest,

    /**
     * The ScoreResponse model constructor.
     * @property {module:model/ScoreResponse}
     */
    ScoreResponse,

    /**
     * The TournamentPlayer model constructor.
     * @property {module:model/TournamentPlayer}
     */
    TournamentPlayer,

    /**
     * The TournamentRequest model constructor.
     * @property {module:model/TournamentRequest}
     */
    TournamentRequest,

    /**
     * The TournamentResponse model constructor.
     * @property {module:model/TournamentResponse}
     */
    TournamentResponse,

    /**
     * The TournamentResponseParticipantsInner model constructor.
     * @property {module:model/TournamentResponseParticipantsInner}
     */
    TournamentResponseParticipantsInner,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
