/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TournamentApi);
  }
})(this, function (expect, TournamentApi) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new TournamentApi.LocalPlayApi();
  });

  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === "function") return object[getter]();
    else return object[property];
  };

  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === "function") object[setter](value);
    else object[property] = value;
  };

  describe("LocalPlayApi", function () {
    describe("apiMatchesLocalGet", function () {
      it("should call apiMatchesLocalGet successfully", function (done) {
        //uncomment below and update the code to test apiMatchesLocalGet
        //instance.apiMatchesLocalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe("apiMatchesLocalScorePatch", function () {
      it("should call apiMatchesLocalScorePatch successfully", function (done) {
        //uncomment below and update the code to test apiMatchesLocalScorePatch
        //instance.apiMatchesLocalScorePatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe("apiTournamentsLocalGet", function () {
      it("should call apiTournamentsLocalGet successfully", function (done) {
        //uncomment below and update the code to test apiTournamentsLocalGet
        //instance.apiTournamentsLocalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe("apiTournamentsLocalPost", function () {
      it("should call apiTournamentsLocalPost successfully", function (done) {
        // モックデータやテスト用のデータを用意する
        var tournamentData = {
          players: ["Alice", "Bob", "Charlie", "David"], // 2の累乗のプレイヤー数
        };

        // API メソッドを呼び出す
        instance.apiTournamentsLocalPost(
          tournamentData,
          function (error, response) {
            if (error) {
              // エラーが発生した場合は、テストを失敗させる
              console.log("Error:", error); // エラーメッセージをログに出力

              return done(error);
            }

            // レスポンスがオブジェクトであることを確認
            expect(response).to.be.an("object");

            // tournament_id がレスポンスに含まれていることを確認
            expect(response).to.have.property("tournament_id");
            expect(response.tournament_id).to.be.a("number"); // tournament_id が数値であること

            // participants が含まれていることを確認
            expect(response).to.have.property("participants");
            expect(response.participants).to.be.an("array"); // participants が配列であること

            // participants の各要素が期待通りの構造を持つか確認
            response.participants.forEach(function (participant) {
              expect(participant).to.have.property("player"); // player が含まれていること
              expect(participant.player).to.have.property("name"); // player.name が含まれていること
              expect(participant.player.name).to.be.a("string"); // player.name が文字列であること

              expect(participant).to.have.property("tournament_players"); // tournament_players が含まれていること
              expect(participant.tournament_players).to.have.property(
                "victory_count"
              ); // 勝利数が含まれていること
              expect(participant.tournament_players.victory_count).to.be.a(
                "number"
              ); // victory_count が数値であること

              expect(participant).to.have.property("next_player"); // next_player が含まれていること
              expect(participant.next_player).to.be.a("boolean"); // next_player がブール値であること
            });

            // テストが成功したことを示す
            done();
          }
        );
      });
    });
  });
});
