/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    // AMD.
    define(["expect.js", process.cwd() + "/src/index"], factory);
  } else if (typeof module === "object" && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require("expect.js"), require(process.cwd() + "/src/index"));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TournamentApi);
  }
})(this, function (expect, TournamentApi) {
  "use strict";

  var instance;

  beforeEach(function () {
    instance = new TournamentApi.LocalPlayApi();
  });

  var checkPlayerMatchDetails = function(player) {
    expect(player).to.have.property('player');
    expect(player.player).to.have.property('name');
    expect(player.player.name).to.be.a('string');
    expect(player).to.have.property('match_details');
    expect(player.match_details).to.have.property('player_id');
    expect(player.match_details.player_id).to.be.a('number');
    expect(player.match_details).to.have.property('match_id');
    expect(player.match_details.match_id).to.be.a('number');
    expect(player.match_details).to.have.property('score');
    expect(player.match_details.score).to.be.a('number');
  };

  describe("LocalPlayApi", function () {
    describe("apiMatchesLocalGet", function () {
      it("should call apiMatchesLocalGet successfully", function (done) {
        instance.apiMatchesLocalGet(function(error, response) {
          if (error) return done(error);
          try {
            expect(response).to.be.an('object');
            expect(response).to.have.property('players');
            expect(response.players).to.be.an('array');
            response.players.forEach(checkPlayerMatchDetails);
            done();
          } catch (e) {
            done(e);
          }
        });
      });
    });

    describe("apiMatchesLocalScorePatch", function () {
      it("should call apiMatchesLocalScorePatch successfully", function (done) {
        var scoreData = {
          match_id: 1,
          player_id: 1
        };
        instance.apiMatchesLocalScorePatch(scoreData, function(error, response) {
          if (error) return done(error);
          try {
            expect(response).to.be.an('object');
            expect(response).to.have.property('players');
            expect(response.players).to.be.an('array');
            response.players.forEach(checkPlayerMatchDetails);
            expect(response).to.have.property('end_match');
            expect(response.end_match).to.be.a('boolean');
            done();
          } catch (e) {
            done(e);
          }
        });
      });
    });

    describe("apiTournamentsLocalGet", function () {
      it("should call apiTournamentsLocalGet successfully", function (done) {
        instance.apiTournamentsLocalGet(function(error, response) {
          if (error) return done(error);
          try {
            expect(response).to.be.an('object');
            expect(response).to.have.property('participants');
            expect(response.participants).to.be.an('array');
            response.participants.forEach(function(participant) {
              expect(participant).to.have.property('player');
              expect(participant.player).to.have.property('name');
              expect(participant.player.name).to.be.a('string');
              expect(participant).to.have.property('tournament_players');
              expect(participant.tournament_players).to.have.property('victory_count');
              expect(participant.tournament_players.victory_count).to.be.a('number');
              expect(participant).to.have.property('next_player');
              expect(participant.next_player).to.be.a('boolean');
            });
            expect(response).to.have.property('tournament_id');
            expect(response.tournament_id).to.be.a('number');
            done();
          } catch (e) {
            done(e);
          }
        });
      });
    });

    describe("apiTournamentsLocalPost", function () {
      it("should call apiTournamentsLocalPost successfully", function (done) {
        var tournamentData = {
          players: ["Alice", "Bob", "Charlie", "David"]
        };

        instance.apiTournamentsLocalPost(tournamentData, function (error, response) {
          if (error) return done(error);
          try {
            expect(response).to.be.an('object');
            expect(response).to.have.property('tournament_id');
            expect(response.tournament_id).to.be.a('number');
            expect(response).to.have.property('participants');
            expect(response.participants).to.be.an('array');
            response.participants.forEach(function (participant) {
              expect(participant).to.have.property('player');
              expect(participant.player).to.have.property('name');
              expect(participant.player.name).to.be.a('string');
              expect(participant).to.have.property('tournament_players');
              expect(participant.tournament_players).to.have.property('victory_count');
              expect(participant.tournament_players.victory_count).to.be.a('number');
              expect(participant).to.have.property('next_player');
              expect(participant.next_player).to.be.a('boolean');
            });
            done();
          } catch (e) {
            done(e);
          }
        });
      });
    });
  });
});

