/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MatchDetail model module.
 * @module model/MatchDetail
 * @version 1.0.0
 */
class MatchDetail {
    /**
     * Constructs a new <code>MatchDetail</code>.
     * @alias module:model/MatchDetail
     */
    constructor() { 
        
        MatchDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatchDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchDetail} obj Optional instance to populate.
     * @return {module:model/MatchDetail} The populated <code>MatchDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchDetail();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'Number');
            }
            if (data.hasOwnProperty('match_id')) {
                obj['match_id'] = ApiClient.convertToType(data['match_id'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchDetail</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} player_id
 */
MatchDetail.prototype['player_id'] = undefined;

/**
 * @member {Number} match_id
 */
MatchDetail.prototype['match_id'] = undefined;

/**
 * @member {Number} score
 */
MatchDetail.prototype['score'] = undefined;






export default MatchDetail;

