/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchResponsePlayersInner from './MatchResponsePlayersInner';

/**
 * The MatchResponse model module.
 * @module model/MatchResponse
 * @version 1.0.0
 */
class MatchResponse {
    /**
     * Constructs a new <code>MatchResponse</code>.
     * @alias module:model/MatchResponse
     */
    constructor() { 
        
        MatchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchResponse} obj Optional instance to populate.
     * @return {module:model/MatchResponse} The populated <code>MatchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchResponse();

            if (data.hasOwnProperty('match_id')) {
                obj['match_id'] = ApiClient.convertToType(data['match_id'], 'Number');
            }
            if (data.hasOwnProperty('players')) {
                obj['players'] = ApiClient.convertToType(data['players'], [MatchResponsePlayersInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchResponse</code>.
     */
    static validateJSON(data) {
        if (data['players']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['players'])) {
                throw new Error("Expected the field `players` to be an array in the JSON data but got " + data['players']);
            }
            // validate the optional field `players` (array)
            for (const item of data['players']) {
                MatchResponsePlayersInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} match_id
 */
MatchResponse.prototype['match_id'] = undefined;

/**
 * @member {Array.<module:model/MatchResponsePlayersInner>} players
 */
MatchResponse.prototype['players'] = undefined;






export default MatchResponse;

