/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchDetail from './MatchDetail';
import Player from './Player';

/**
 * The MatchResponsePlayersInner model module.
 * @module model/MatchResponsePlayersInner
 * @version 1.0.0
 */
class MatchResponsePlayersInner {
    /**
     * Constructs a new <code>MatchResponsePlayersInner</code>.
     * @alias module:model/MatchResponsePlayersInner
     */
    constructor() { 
        
        MatchResponsePlayersInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatchResponsePlayersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchResponsePlayersInner} obj Optional instance to populate.
     * @return {module:model/MatchResponsePlayersInner} The populated <code>MatchResponsePlayersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchResponsePlayersInner();

            if (data.hasOwnProperty('player')) {
                obj['player'] = Player.constructFromObject(data['player']);
            }
            if (data.hasOwnProperty('matchdetail')) {
                obj['matchdetail'] = MatchDetail.constructFromObject(data['matchdetail']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchResponsePlayersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchResponsePlayersInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `player`
        if (data['player']) { // data not null
          Player.validateJSON(data['player']);
        }
        // validate the optional field `matchdetail`
        if (data['matchdetail']) { // data not null
          MatchDetail.validateJSON(data['matchdetail']);
        }

        return true;
    }


}



/**
 * @member {module:model/Player} player
 */
MatchResponsePlayersInner.prototype['player'] = undefined;

/**
 * @member {module:model/MatchDetail} matchdetail
 */
MatchResponsePlayersInner.prototype['matchdetail'] = undefined;






export default MatchResponsePlayersInner;

