/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MatchDetails model module.
 * @module model/MatchDetails
 * @version 1.0.0
 */
class MatchDetails {
    /**
     * Constructs a new <code>MatchDetails</code>.
     * @alias module:model/MatchDetails
     * @param playerId {Number} 
     * @param matchId {Number} 
     */
    constructor(playerId, matchId) { 
        
        MatchDetails.initialize(this, playerId, matchId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId, matchId) { 
        obj['player_id'] = playerId;
        obj['match_id'] = matchId;
    }

    /**
     * Constructs a <code>MatchDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchDetails} obj Optional instance to populate.
     * @return {module:model/MatchDetails} The populated <code>MatchDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchDetails();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'Number');
            }
            if (data.hasOwnProperty('match_id')) {
                obj['match_id'] = ApiClient.convertToType(data['match_id'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchDetails</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MatchDetails.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

MatchDetails.RequiredProperties = ["player_id", "match_id"];

/**
 * @member {Number} player_id
 */
MatchDetails.prototype['player_id'] = undefined;

/**
 * @member {Number} match_id
 */
MatchDetails.prototype['match_id'] = undefined;

/**
 * @member {Number} score
 */
MatchDetails.prototype['score'] = undefined;






export default MatchDetails;

