/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchDetails from './MatchDetails';

/**
 * The Score model module.
 * @module model/Score
 * @version 1.0.0
 */
class Score {
    /**
     * Constructs a new <code>Score</code>.
     * @alias module:model/Score
     */
    constructor() { 
        
        Score.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Score</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Score} obj Optional instance to populate.
     * @return {module:model/Score} The populated <code>Score</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Score();

            if (data.hasOwnProperty('match_details')) {
                obj['match_details'] = MatchDetails.constructFromObject(data['match_details']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Score</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Score</code>.
     */
    static validateJSON(data) {
        // validate the optional field `match_details`
        if (data['match_details']) { // data not null
          MatchDetails.validateJSON(data['match_details']);
        }

        return true;
    }


}



/**
 * @member {module:model/MatchDetails} match_details
 */
Score.prototype['match_details'] = undefined;






export default Score;

