/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TournamentPlayer model module.
 * @module model/TournamentPlayer
 * @version 1.0.0
 */
class TournamentPlayer {
    /**
     * Constructs a new <code>TournamentPlayer</code>.
     * @alias module:model/TournamentPlayer
     * @param victoryCount {Number} 
     */
    constructor(victoryCount) { 
        
        TournamentPlayer.initialize(this, victoryCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, victoryCount) { 
        obj['victory_count'] = victoryCount;
    }

    /**
     * Constructs a <code>TournamentPlayer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TournamentPlayer} obj Optional instance to populate.
     * @return {module:model/TournamentPlayer} The populated <code>TournamentPlayer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TournamentPlayer();

            if (data.hasOwnProperty('victory_count')) {
                obj['victory_count'] = ApiClient.convertToType(data['victory_count'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TournamentPlayer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TournamentPlayer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TournamentPlayer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TournamentPlayer.RequiredProperties = ["victory_count"];

/**
 * @member {Number} victory_count
 */
TournamentPlayer.prototype['victory_count'] = undefined;






export default TournamentPlayer;

