/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TournamentResponseParticipantsInner from './TournamentResponseParticipantsInner';

/**
 * The TournamentResponse model module.
 * @module model/TournamentResponse
 * @version 1.0.0
 */
class TournamentResponse {
    /**
     * Constructs a new <code>TournamentResponse</code>.
     * @alias module:model/TournamentResponse
     */
    constructor() { 
        
        TournamentResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TournamentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TournamentResponse} obj Optional instance to populate.
     * @return {module:model/TournamentResponse} The populated <code>TournamentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TournamentResponse();

            if (data.hasOwnProperty('participants')) {
                obj['participants'] = ApiClient.convertToType(data['participants'], [TournamentResponseParticipantsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TournamentResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TournamentResponse</code>.
     */
    static validateJSON(data) {
        if (data['participants']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['participants'])) {
                throw new Error("Expected the field `participants` to be an array in the JSON data but got " + data['participants']);
            }
            // validate the optional field `participants` (array)
            for (const item of data['participants']) {
                TournamentResponseParticipantsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/TournamentResponseParticipantsInner>} participants
 */
TournamentResponse.prototype['participants'] = undefined;






export default TournamentResponse;

