/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Player from './Player';
import TournamentPlayer from './TournamentPlayer';

/**
 * The TournamentResponseParticipantsInner model module.
 * @module model/TournamentResponseParticipantsInner
 * @version 1.0.0
 */
class TournamentResponseParticipantsInner {
    /**
     * Constructs a new <code>TournamentResponseParticipantsInner</code>.
     * @alias module:model/TournamentResponseParticipantsInner
     */
    constructor() { 
        
        TournamentResponseParticipantsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TournamentResponseParticipantsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TournamentResponseParticipantsInner} obj Optional instance to populate.
     * @return {module:model/TournamentResponseParticipantsInner} The populated <code>TournamentResponseParticipantsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TournamentResponseParticipantsInner();

            if (data.hasOwnProperty('player')) {
                obj['player'] = Player.constructFromObject(data['player']);
            }
            if (data.hasOwnProperty('tournamentplayer')) {
                obj['tournamentplayer'] = TournamentPlayer.constructFromObject(data['tournamentplayer']);
            }
            if (data.hasOwnProperty('next_player')) {
                obj['next_player'] = ApiClient.convertToType(data['next_player'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TournamentResponseParticipantsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TournamentResponseParticipantsInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `player`
        if (data['player']) { // data not null
          Player.validateJSON(data['player']);
        }
        // validate the optional field `tournamentplayer`
        if (data['tournamentplayer']) { // data not null
          TournamentPlayer.validateJSON(data['tournamentplayer']);
        }

        return true;
    }


}



/**
 * @member {module:model/Player} player
 */
TournamentResponseParticipantsInner.prototype['player'] = undefined;

/**
 * @member {module:model/TournamentPlayer} tournamentplayer
 */
TournamentResponseParticipantsInner.prototype['tournamentplayer'] = undefined;

/**
 * @member {Boolean} next_player
 */
TournamentResponseParticipantsInner.prototype['next_player'] = undefined;






export default TournamentResponseParticipantsInner;

