/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TournamentRequest model module.
 * @module model/TournamentRequest
 * @version 1.0.0
 */
class TournamentRequest {
    /**
     * Constructs a new <code>TournamentRequest</code>.
     * @alias module:model/TournamentRequest
     * @param players {Array.<String>} 
     */
    constructor(players) { 
        
        TournamentRequest.initialize(this, players);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, players) { 
        obj['players'] = players;
    }

    /**
     * Constructs a <code>TournamentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TournamentRequest} obj Optional instance to populate.
     * @return {module:model/TournamentRequest} The populated <code>TournamentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TournamentRequest();

            if (data.hasOwnProperty('players')) {
                obj['players'] = ApiClient.convertToType(data['players'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TournamentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TournamentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TournamentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['players'])) {
            throw new Error("Expected the field `players` to be an array in the JSON data but got " + data['players']);
        }

        return true;
    }


}

TournamentRequest.RequiredProperties = ["players"];

/**
 * @member {Array.<String>} players
 */
TournamentRequest.prototype['players'] = undefined;






export default TournamentRequest;

