services:
  nginx:
    container_name: nginx
    image: nginx:1.26.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # TODO mount ssl/tls certificate volume
      - ./nginx.conf:/etc/nginx/nginx.conf
