# Generated by Django 4.2 on 2025-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='is_left_side',
            field=models.BooleanField(default=True),
        ),
    ]
