/**
 * Tournament API
 * トーナメント、試合、プレイヤーの管理用API。
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import MatchStatus from '../model/MatchStatus';
import Score from '../model/Score';
import TournamentRequest from '../model/TournamentRequest';
import TournamentResponse from '../model/TournamentResponse';

/**
* LocalPlay service.
* @module api/LocalPlayApi
* @version 1.0.0
*/
export default class LocalPlayApi {

    /**
    * Constructs a new LocalPlayApi. 
    * @alias module:api/LocalPlayApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiMatchesLocalGet operation.
     * @callback module:api/LocalPlayApi~apiMatchesLocalGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MatchStatus} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 試合の開始
     * 次の試合の詳細を取得します。
     * @param {module:api/LocalPlayApi~apiMatchesLocalGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MatchStatus}
     */
    apiMatchesLocalGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MatchStatus;
      return this.apiClient.callApi(
        '/api/matches/local', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiMatchesLocalScorePatch operation.
     * @callback module:api/LocalPlayApi~apiMatchesLocalScorePatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MatchStatus} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * スコアの更新
     * 試合中のプレイヤーのスコアを増加させます。
     * @param {module:model/Score} score 
     * @param {module:api/LocalPlayApi~apiMatchesLocalScorePatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MatchStatus}
     */
    apiMatchesLocalScorePatch(score, callback) {
      let postBody = score;
      // verify the required parameter 'score' is set
      if (score === undefined || score === null) {
        throw new Error("Missing the required parameter 'score' when calling apiMatchesLocalScorePatch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = MatchStatus;
      return this.apiClient.callApi(
        '/api/matches/local/score', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiTournamentsLocalGet operation.
     * @callback module:api/LocalPlayApi~apiTournamentsLocalGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TournamentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * トーナメントの表示
     * 試合からトーナメントに戻るためのAPI。
     * @param {module:api/LocalPlayApi~apiTournamentsLocalGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TournamentResponse}
     */
    apiTournamentsLocalGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TournamentResponse;
      return this.apiClient.callApi(
        '/api/tournaments/local', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiTournamentsLocalPost operation.
     * @callback module:api/LocalPlayApi~apiTournamentsLocalPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TournamentResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * トーナメントの作成
     * プレイヤーのリストを使用して新しいトーナメントを作成します。プレイヤーの数は2の累乗（例：2、4、8、16）でなければなりません。
     * @param {module:model/TournamentRequest} tournamentRequest 
     * @param {module:api/LocalPlayApi~apiTournamentsLocalPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TournamentResponse}
     */
    apiTournamentsLocalPost(tournamentRequest, callback) {
      let postBody = tournamentRequest;
      // verify the required parameter 'tournamentRequest' is set
      if (tournamentRequest === undefined || tournamentRequest === null) {
        throw new Error("Missing the required parameter 'tournamentRequest' when calling apiTournamentsLocalPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TournamentResponse;
      return this.apiClient.callApi(
        '/api/tournaments/local', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
