# Djangoの開発用。グローバルdocker-compose.ymlができたら削除する
services:
  # バックエンドのサービス
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development_djangoserver # 開発用のDockerfileのターゲット
    ports:
      - "8000:8000"
    networks:
      - pong_network
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: pong_db
      POSTGRES_USER: pong_user
      POSTGRES_PASSWORD: pass
    networks:
      - pong_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pong_user"]
      interval: 15s
      retries: 5

volumes:
  postgres_data:

networks:
  pong_network:
    driver: bridge
