name: Auto-assign PR creator

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-pr-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR creator
        uses: actions/github-script@v7
        with:
          script: |
            const prCreator = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;
            
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              assignees: [prCreator]
            });
            
            console.log(`Assigned PR #${prNumber} to ${prCreator}`);
